openapi: 3.0.0
info:
  title: Reserv API
  description: Reserv API
  version: 1.0.0

servers:
  - url: https://reserv-production.up.railway.app/
    description: Reserv production server

tags:
  - name: Properties
    description: API for managing property listings
  - name: Images
    description: API for managing images

components:
  schemas:
    CreateProperty:
      type: object
      properties:
        title:
          type: string
          description: Title of the property
        description:
          type: string
          description: Description of the property
        price_per_night_cents:
          type: integer
          description: Price per night in cents
        currency:
          type: string
          description: Currency code (e.g., USD, BRL)
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - title
        - description
        - price_per_night_cents
        - currency
        - updated_at
    ReturnProperty:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the property
        host_id:
          type: string
          format: uuid
          description: Unique identifier for the host
        title:
          type: string
          description: Title of the property
        description:
          type: string
          description: Description of the property
        price_per_night_cents:
          type: integer
          description: Price per night in cents
        currency:
          type: string
          description: Currency code (e.g., USD, BRL)
        amenities:
          type: array
          items:
            $ref: '#/components/schemas/Amenity'
        images:
          type: array
          items:
            $ref: '#/components/schemas/PropertyImage'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - host_id
        - title
        - description
        - price_per_night_cents
        - currency
        - updated_at

    Amenity:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the amenity
        name:
          type: string
          description: Name of the amenity
        created_at:
          type: string
          format: date-time
      required:
        - id
        - name
        - created_at

    CreatePropertyImage:
      type: object
      properties:
        property_id:
          type: string
          format: uuid
          description: Unique identifier for the property
        host_id:
          type: string
          format: uuid
          description: Unique identifier for the host
      required:
        - property_id
        - host_id

    PropertyImage:
      type: object
      properties:
        id:
          type: string
          description: Cloudflare image ID
        host_id:
          type: string
          format: uuid
          description: Unique identifier for the host
        created_at:
          type: string
          format: date-time
        property_id:
          type: string
          format: uuid
          description: Unique identifier for the property
        cloudflare_id:
          type: string
          format: uuid
        filename:
          type: string
          description: Filename of the image
      required:
        - id
        - host_id
        - property_id
        - cloudflare_id
        - filename
        - created_at

    ReturnPropertyImage:
      type: object
      properties:
        cloudflare_id:
          type: string
          format: uuid
          description: Unique identifier for the image
        filename:
          type: string
          description: Filename of the image
      required:
        - cloudflare_id
        - filename


    APIError:
      type: object
      properties:
        message:
          type: string
          description: Error message
        details:
          type: string
          description: Detailed error information
        status:
          type: integer
          description: HTTP status code
      required:
        - message
        - status

paths:
  /properties:
    get:
      tags:
        - Properties
      summary: List all properties
      description: Returns a list of all properties with their amenities
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReturnProperty'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'

    post:
      tags:
        - Properties
      summary: Create a new property
      description: Creates a new property listing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProperty'
      responses:
        '201':
          description: Property created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'

  /properties/{id}:
    parameters:
      - name: id
        in: query
        required: true
        schema:
          type: string
          format: uuid
        description: Property ID

    get:
      tags:
        - Properties
      summary: Get property by ID
      description: Returns a single property by its ID
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReturnProperty'
        '404':
          description: Property not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'

    put:
      tags:
        - Properties
      summary: Update property
      description: Updates an existing property
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProperty'
      responses:
        '200':
          description: Property updated successfully
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '404':
          description: Property not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'

    delete:
      tags:
        - Properties
      summary: Delete property
      description: Deletes a property and its associated amenities
      responses:
        '200':
          description: Property deleted successfully
        '404':
          description: Property not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'

  /images:
    post:
      tags:
        - Images
      summary: Upload an image
      description: Uploads an image to Cloudflare Images
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Upload an image and associate it with a property and a host
      responses:
        '201':
          description: Image uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePropertyImage'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
